In [ ]:
import numpy as np

## Task 1

In [30]:
array_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# array_2D = np.array([np.random.randint(10, 50) for _ in range(12)]).reshape(3, 4)
array_2D = np.random.randint(10, 50, size=(3, 4))
array_3D = np.zeros(18).reshape(2, 3, 3)

print(array_1D.shape, array_1D.dtype, array_1D.ndim, array_1D.size)
print(array_2D.shape, array_2D.dtype, array_2D.ndim, array_2D.size)
print(array_3D.shape, array_3D.dtype, array_3D.ndim, array_3D.size)

(10,) int32 1 10
(3, 4) int32 2 12
(2, 3, 3) float64 3 18


## Task 2

In [19]:
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
int_array = float_array.astype(int)
print(float_array, int_array)
print(f'Converting Float to Int slices the decimal part of the float. {float_array[0]} -> {int_array[0]}')

[1.1 2.2 3.3 4.4 5.5] [1 2 3 4 5]
Converting Float to Int slices the decimal part of the float. 1.1 -> 1


## Task 3

In [31]:
# a = np.array([np.random.randint(1, 20) for _ in range(5)])
# b = np.array([np.random.randint(1, 20) for _ in range(5)])
a = np.random.randint(1, 20, size=5)
b = np.random.randint(1, 20, size=5)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
sqroot = np.sqrt(a)
exp = np.exp(b)
print(sqroot, exp)

[32 14 19 16 24]
[  0 -10   7  -6   0]
[256  24  78  55 144]
[1.         0.16666667 2.16666667 0.45454545 1.        ]
[4.         1.41421356 3.60555128 2.23606798 3.46410162] [8.88611052e+06 1.62754791e+05 4.03428793e+02 5.98741417e+04
 1.62754791e+05]


## Task 4

In [ ]:
# ex_array = np.array([np.random.randint(1, 100) for _ in range(20)]).reshape(4, 5)
ex_array = np.random.randint(1, 100, size=(4, 5))
print(ex_array)
# Get the first two rows
print(ex_array[:2])
# Get the last three columns
print(ex_array[:, -3:])
# Get the first two rows and the last two columns
print(ex_array[2:4, 1:4])

# Get all values greater than 50
g_50_array = ex_array[ex_array > 50]
print(g_50_array)
# Replace all values less than 20 with 0
ex_array[ex_array < 20] = 0
print(ex_array)

[[28 29 92 99  3]
 [36 18 17 75 77]
 [71 77 78 44 49]
 [53 50 63 32 45]]
[[28 29 92 99  3]
 [36 18 17 75 77]]
[[92 99  3]
 [17 75 77]
 [78 44 49]
 [63 32 45]]
[[77 78 44]
 [50 63 32]]
[92 99 75 77 71 77 78 53 63]
[[28 29 92 99  0]
 [36  0  0 75 77]
 [71 77 78 44 49]
 [53 50 63 32 45]]


## Task 5

In [52]:
array_3D = np.random.randint(1, 10, size=(3, 2, 4))
print(array_3D)
print(array_3D.T)
print(array_3D.swapaxes(0, 1))

[[[8 1 4 5]
  [7 9 9 1]]

 [[9 9 4 6]
  [7 2 8 9]]

 [[8 8 9 9]
  [7 8 6 6]]]
[[[8 9 8]
  [7 7 7]]

 [[1 9 8]
  [9 2 8]]

 [[4 4 9]
  [9 8 6]]

 [[5 6 9]
  [1 9 6]]]
[[[8 1 4 5]
  [9 9 4 6]
  [8 8 9 9]]

 [[7 9 9 1]
  [7 2 8 9]
  [7 8 6 6]]]


## Task 6

In [69]:
array_1D = np.random.random(size=10)
array_2D = np.random.randint(5, 15, size=(3, 3))

rand_gen = np.random.default_rng(seed=42)
array_1D = rand_gen.integers(5, 15, size=5)
print(array_1D)
print('Seeding the random number generator is useful for reproducibility.')


[ 5 12 11  9  9]
Seeding the random number generator is useful for reproducibility.


## Task 7

In [91]:
array_1D = np.random.randint(1, 50, size=50)
print(np.sort(array_1D))
print(np.sort(array_1D)[::-1])
array_1D_2 = np.random.randint(10, 60, size=50)
print(np.unique(array_1D_2))
print(np.intersect1d(array_1D, array_1D_2))
print(np.union1d(array_1D, array_1D_2))
print(np.setdiff1d(array_1D, array_1D_2))

[ 1  3  3  4  6  7  8 13 14 15 16 16 17 17 17 17 18 18 18 18 19 20 20 21
 22 23 23 24 27 27 28 29 29 29 30 31 31 32 34 34 35 35 38 38 39 43 43 44
 44 49]
[49 44 44 43 43 39 38 38 35 35 34 34 32 31 31 30 29 29 29 28 27 27 24 23
 23 22 21 20 20 19 18 18 18 18 17 17 17 17 16 16 15 14 13  8  7  6  4  3
  3  1]
[11 12 14 15 18 19 20 23 24 25 27 28 30 31 32 33 34 37 38 39 42 43 45 46
 47 48 49 50 53 54 55 56 57 59]
[14 15 18 19 20 23 24 27 28 30 31 32 34 38 39 43 49]
[ 1  3  4  6  7  8 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29
 30 31 32 33 34 35 37 38 39 42 43 44 45 46 47 48 49 50 53 54 55 56 57 59]
[ 1  3  4  6  7  8 13 16 17 21 22 29 35 44]
